#version 460
#extension GL_ARB_gpu_shader_int64 : require
#extension GL_ARB_shader_clock : require
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_ray_tracing : require

#include "Heatmap.glsl"
#include "Random.glsl"
#include "RayPayload.glsl"
#include "RayVertex.glsl"
#include "UniformBufferObject.glsl"

layout(binding = 0, set = 0) uniform accelerationStructureEXT Scene;
layout(binding = 1, rgba32f) uniform image2D AccumulationImage;
layout(binding = 2, rgba8) uniform image2D OutputImage;
layout(binding = 3) readonly uniform UniformBufferObjectStruct { UniformBufferObject Camera; };

layout(binding = 12) buffer RayCounter { uint rayCounter; };
layout(binding = 13) buffer RayVertexBuffer { RayVertex Vertices[]; };
layout(binding = 14) buffer RayInfoBuffer { RayInfo info[]; };

layout(location = 0) rayPayloadEXT RayPayload Ray;

float normpdf(in float x, in float sigma)
{
	return 0.39894*exp(-0.5*x*x/(sigma*sigma))/sigma;
}

float normpdf3(in vec3 v, in float sigma)
{
	return 0.39894*exp(-0.5*dot(v,v)/(sigma*sigma))/sigma;
}

void main() 
{
	const uint64_t clock = Camera.ShowHeatmap ? clockARB() : 0;

	// Initialise separate random seeds for the pixel and the rays.
	// - pixel: we want the same random seed for each pixel to get a homogeneous anti-aliasing.
	// - ray: we want a noisy random seed, different for each pixel.
	uint pixelRandomSeed = Camera.RandomSeed;
	Ray.RandomSeed = InitRandomSeed(InitRandomSeed(gl_LaunchIDEXT.x, gl_LaunchIDEXT.y), Camera.TotalNumberOfSamples);

	vec3 pixelColor = vec3(0);

	// Count the rays and set the index
	uint rayIndex = -1;

	uint i = 0;
	uint rayOffset = Camera.NumberOfBounces + 1;


	// Accumulate all the rays for this pixels.
	for (uint s = 0; s < Camera.NumberOfSamples; ++s)
	{
		//if (Camera.NumberOfSamples != Camera.TotalNumberOfSamples) break;
		const vec2 pixel = vec2(gl_LaunchIDEXT.x + RandomFloat(pixelRandomSeed), gl_LaunchIDEXT.y + RandomFloat(pixelRandomSeed));
		const vec2 uv = (pixel / gl_LaunchSizeEXT.xy) * 2.0 - 1.0;

		vec2 offset = Camera.Aperture/2 * RandomInUnitDisk(Ray.RandomSeed);
		vec4 origin = Camera.ModelViewInverse * vec4(offset, 0, 1);
		vec4 target = Camera.ProjectionInverse * (vec4(uv.x, uv.y, 1, 1));
		vec4 direction = Camera.ModelViewInverse * vec4(normalize(target.xyz * Camera.FocusDistance - vec3(offset, 0)), 0);
		vec3 rayColor = vec3(1);

		// Ray scatters are handled in this loop. There are no recursive traceRayEXT() calls in other shaders.
		for (uint b = 0; b <= Camera.NumberOfBounces; ++b)
		{
			const float tMin = 0.001;
			const float tMax = 10000.0;

			// If we've exceeded the ray bounce limit without hitting a light source, no light is gathered.
			// Light emitting materials never scatter in this implementation, allowing us to make this logical shortcut.
			if (b == Camera.NumberOfBounces) 
			{
				rayColor = vec3(0, 0, 0);
				break;
			}

			traceRayEXT(
				Scene, gl_RayFlagsNoneEXT, 0xff, 
				0 /*sbtRecordOffset*/, 0 /*sbtRecordStride*/, 0 /*missIndex*/, 
				origin.xyz, tMin, direction.xyz, tMax, 0 /*payload*/);

			const vec3 hitColor = Ray.ColorAndDistance.rgb;
			const float t = Ray.ColorAndDistance.w;
			const bool isScattered = Ray.ScatterDirection.w > 0;

			rayColor *= hitColor;

			// Trace missed, or end of trace.
			if (t < 0 || !isScattered)
			{				
				break;
			}

			// Only check the first sample for each pixel
			// If first bounce and did not miss, increment ray counter and store ray info
			if (rayIndex == -1 && s == 0 && b == 0)
			{
				// Atomic Increment, implemented with busy-waiting
				// TODO: isolate this into a function for reusability.
				uint oldCounter, assumedCounter;
				do
				{
					assumedCounter = rayCounter;

					if (assumedCounter >= Camera.MaxRays)
						break;

					oldCounter = atomicCompSwap(rayCounter, assumedCounter, assumedCounter + 1);

					if (oldCounter == assumedCounter)
					{
				        rayIndex = assumedCounter;
				    }
				} while (oldCounter != assumedCounter);

				if (rayIndex != -1) {
					RayVertex vertex;
					vertex.Position = origin.xyz;
					vertex.Color = vec4(1.0);

					Vertices[rayIndex * rayOffset] = vertex;
					Vertices[rayIndex * rayOffset] = vertex;
					i++;

					info[rayIndex].offset = rayOffset;
					info[rayIndex].count  = i;
				}
			}

			// Trace hit.
			origin = origin + t * direction;
			direction = vec4(Ray.ScatterDirection.xyz, 0);

			if (rayIndex != -1 && s == 0)
			{
				RayVertex vertex;
				vertex.Position = origin.xyz;
				vertex.Color = vec4(rayColor, 1.0);
				Vertices[rayIndex * rayOffset + i] = vertex;
				i++;

				info[rayIndex].offset = rayOffset;
				info[rayIndex].count  = i;
			}
		}

		pixelColor += rayColor;
	}

	const bool accumulate = Camera.NumberOfSamples != Camera.TotalNumberOfSamples;
	const vec3 accumulatedColor = (accumulate ? imageLoad(AccumulationImage, ivec2(gl_LaunchIDEXT.xy)) : vec4(0)).rgb + pixelColor;

	pixelColor = accumulatedColor / Camera.TotalNumberOfSamples;

	// Apply raytracing-in-one-weekend gamma correction.
	pixelColor = sqrt(pixelColor);

	//heatmap
	if (Camera.ShowHeatmap)
	{
		const uint64_t deltaTime = clockARB() - clock;
		const float heatmapScale = 1000000.0f * Camera.HeatmapScale * Camera.HeatmapScale;
		const float deltaTimeScaled = clamp(float(deltaTime) / heatmapScale, 0.0f, 1.0f);

		pixelColor = heatmap(deltaTimeScaled);
	}

	imageStore(AccumulationImage, ivec2(gl_LaunchIDEXT.xy), vec4(accumulatedColor, 0));
    imageStore(OutputImage, ivec2(gl_LaunchIDEXT.xy), vec4(pixelColor, 0));

		//====================[BILATERAL FILTER]==========================

	const float SIGMA = 10.0;
	const float BSIGMA = 1.0;
	const int MSIZE = 15;

	vec2 resolution = imageSize(OutputImage);
	
	for (int width = 0; width < resolution.x; width++) {
		for (int height = 0; height < resolution.y; height++) {
			vec2 pixelPos = vec2(width, height) + vec2(0.5);
			vec3 c = imageLoad(OutputImage, ivec2(pixelPos)).rgb;
			if (accumulate)
			{
				//declare stuff
				const int kSize = (MSIZE-1)/2;
				float kernel[MSIZE];
				vec3 final_colour = vec3(0.0);
		
				//create the 1-D kernel
				float Z = 0.0;
				for (int j = 0; j <= kSize; ++j)
				{
					kernel[kSize+j] = kernel[kSize-j] = normpdf(float(j), SIGMA);
				}
		
		
				vec3 cc;
				float factor;
				float bZ = 1.0/normpdf(0.0, BSIGMA);
				//read out the texels
				for (int i = -kSize; i <= kSize; ++i)
				{
					for (int j = -kSize; j <= kSize; ++j)
					{
						cc = imageLoad(OutputImage, ivec2((0.0, 1.0) - (pixelPos + vec2(float(i),float(j))) / resolution)).rgb;
						factor = normpdf3(cc-c, BSIGMA)*bZ*kernel[kSize+j]*kernel[kSize+i];
						Z += factor;
						final_colour += factor*cc;

					}
				}
		
		
				pixelColor = final_colour/Z;
	
		
			} else {
		
				pixelColor = c;
			}

			//rewrite the output with the filtered image
			 imageStore(OutputImage, ivec2(gl_LaunchIDEXT.xy), vec4(pixelColor, 0));

		}
	
	}



	//=================================================================
}
