#include "ScriptTranspiler.hpp"

namespace {

const char* FieldTypeName(ScriptFieldType type) {
    switch (type) {
    case ScriptFieldType::Float: return "anito::FieldType::Float";
    case ScriptFieldType::Int: return "anito::FieldType::Int";
    case ScriptFieldType::Bool: return "anito::FieldType::Bool";
    case ScriptFieldType::String: return "anito::FieldType::String";
    case ScriptFieldType::Vec3: return "anito::FieldType::Vec3";
    }
    return "anito::FieldType::Float";
}

} // namespace

std::string BuildModuleSource(const std::vector<const ScriptDescriptor*>& scripts) {
    std::string out =
        "// Generated by AnitoScript. Do not edit.\n"
        "#include \"AnitoScriptSDK.hpp\"\n\n"
        "#include <cmath>\n#include <cstring>\n#include <string>\n\n"
        "namespace user {\n\n";

    for (const ScriptDescriptor* script : scripts) out += script->cppSource + "\n";
    out += "} // namespace user\n\nnamespace {\n\n";

    for (const ScriptDescriptor* script : scripts) {
        // A zero-length array is ill-formed, so empty field lists get a placeholder that fieldCount ignores.
        out += "const anito::FieldType kFields_" + script->name + "[] = {";
        if (script->fields.empty()) out += "anito::FieldType::Float";
        for (size_t i = 0; i < script->fields.size(); ++i) {
            out += std::string(i ? ", " : "") + FieldTypeName(script->fields[i].type);
        }
        out += "};\n";
    }

    out += "\nconst anito::ScriptEntry kEntries[] = {\n";
    for (const ScriptDescriptor* script : scripts) {
        out += "    {\"" + script->name + "\",\n"
               "     [](const anito::ScriptContext& ctx) -> anito::ScriptBehaviour* { return new user::" + script->name + "(ctx); },\n"
               "     [](anito::ScriptBehaviour* instance) { delete instance; },\n"
               "     " + std::to_string(script->fields.size()) + ", kFields_" + script->name + "},\n";
    }
    if (scripts.empty()) out += "    {nullptr, nullptr, nullptr, 0, nullptr},\n";
    out += "};\n\n";

    out += "const anito::ModuleInfo kModule = {ANITO_SCRIPT_ABI_VERSION, " + std::to_string(scripts.size()) + ", kEntries};\n\n";
    out += "} // namespace\n\nANITO_SCRIPT_EXPORT const anito::ModuleInfo* AnitoScript_GetModule() { return &kModule; }\n";
    return out;
}
