#pragma once

#define EVENT_ON_APP_INITIALIZE "ONAPPINITIALIZE"
#define EVENT_ON_APP_RUN "ONAPPRUN"
#define EVENT_ON_APP_PLAY "ONAPPPLAY"
#define EVENT_ON_APP_STOPPLAY "ONAPPSTOPPLAY"

#define EVENT_RENDER_START "ONRENDERSTART"
#define EVENT_RENDER_END "ONRENDEREND"
#define EVENT_RENDER_CHANGE "ONRENDERCHANGE"
#define EVENT_UPDATE_EDITOR_OPTIONS "ONUPDATEEDITOROPTIONS"

#define EVENT_ONSCENELOAD "ONSCENELOAD"
#define EVENT_ONSCENEUNLOAD "ONSCENEUNLOAD"
#define EVENT_ONOBJECTCREATED "ONOBJECTCREATED"
#define EVENT_ONOBJECTDESTROYED "ONOBJECTDESTROYED"